# -*- coding: utf-8 -*-
"""IDS Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19iei-O28ZLxx8n_uLv-m7fAAsI4eaeP1
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Step 1: Load and Clean the Data
def load_and_clean_data(file_path):
    # Specify the encoding when reading the CSV file
    data = pd.read_csv('data.csv', encoding='latin-1')  # or 'ISO-8859-1'
    # Drop columns with all null values
    data = data.dropna(axis=1, how='all')
    # Keep columns with at least 50% non-null values
    data = data.loc[:, data.isnull().mean() < 0.5]
    # Rename columns for consistency
    data.columns = data.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(r'[^\w]', '', regex=True)
    # Fill missing values in categorical columns with 'Unknown'
    for col in data.select_dtypes(include=['object']).columns:
        data[col] = data[col].fillna('Unknown')
    # Fill missing values in numerical columns with median
    for col in data.select_dtypes(include=['float64', 'int64']).columns:
        data[col] = data[col].fillna(data[col].median())
    return data

file_path = '/mnt/patient data/data.csv'
data = load_and_clean_data('data.csv')
print(data)

# Step 2: Descriptive Statistics
def descriptive_statistics(data):
    recovery_rate = data['initial_dose_or__dose_is_readjusted']
    recovery_rate = recovery_rate.value_counts(normalize=True) * 100
    print("Recovery Rate by Response to Treatment:")
    print(recovery_rate)

    print("\nDemographics Summary:")
    print(data[['gender', 'age_years', 'residency']].describe(include='all'))

descriptive_statistics(data)

# Step 3: Ordinal Analysis
def ordinal_analysis(data):
    stage_recovery = data.groupby('stage_of_breast_cancer')['initial_dose_or__dose_is_readjusted'].value_counts(normalize=True).unstack()
    print("\nRecovery Rates by Cancer Stage:")
    print(stage_recovery)

ordinal_analysis(data)

# Step 4: Correlation Analysis (Updated)
def correlation_analysis(data):
    # Define the key factors
    key_factors = [
        'age_years',
        'stage_of_breast_cancer',
        'are_you_taking_any_radiation_therapy',
        'are_you_taking_any_hormonal_therapy',
        'initial_dose_or__dose_is_readjusted'
    ]

    # Check for missing columns
    missing_columns = [col for col in key_factors if col not in data.columns]
    if missing_columns:
        print(f"Warning: The following columns are missing from the DataFrame: {missing_columns}")
        key_factors = [col for col in key_factors if col in data.columns]

    if not key_factors:
        print("No valid columns found for correlation analysis. Exiting.")
        return

    # Select only the relevant columns
    data_subset = data[key_factors]

    # Drop rows with missing values
    data_subset = data_subset.dropna()

    if data_subset.empty:
        print("No data available after handling missing values. Exiting.")
        return

    # Encode categorical columns (if applicable)
    encoded_data = pd.get_dummies(data_subset, drop_first=True)

    # Calculate the correlation matrix
    corr_matrix = encoded_data.corr()

    # Create the heatmap
    plt.figure(figsize=(10, 8))  # Adjusted size for better readability
    sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1)
    plt.title('Correlation Heatmap of Key Factors')
    plt.show()
correlation_analysis(data)

# Step 5: Additional Graphs
def additional_graphs(data):

    # Distribution of Recovery Rate Responses
    custom_colors = [ '#F8F8FF', '#4169E1']
    recovery_rate_distribution = data['initial_dose_or__dose_is_readjusted'].value_counts()
    recovery_rate_distribution.plot(kind='pie', autopct='%1.1f%%', figsize=(6, 6),colors=custom_colors)
    plt.title('Distribution of Recovery Rate Responses')
    custom_colors = sns.color_palette("pastel")
    plt.ylabel('')
    plt.show()

     # Recovery Rate with Respect to Age
    plt.figure(figsize=(10, 6))
    sns.boxplot(x='initial_dose_or__dose_is_readjusted', y='age_years', data=data)
    plt.title('Recovery Rate with Respect to Age')
    plt.xlabel('Response to Treatment')
    plt.ylabel('Age')
    plt.show()

       #side effect graph
def side_effect_graph(data):
    # List of columns that represent side effects
    side_effect_columns = ['headache', 'dizziness', 'fainting', 'weekness', 'fatigue']

    # Convert to binary (1 for any occurrence, 0 for no occurrence)
    side_effect_data = data[side_effect_columns].applymap(lambda x: 1 if x > 0 else 0)

    # Calculate the percentage of patients experiencing each side effect
    side_effect_percentages = side_effect_data.mean() * 100

    # Create a bar plot
    plt.figure(figsize=(10, 6))
    ax = sns.barplot(x=side_effect_percentages.index, y=side_effect_percentages.values, palette='viridis')

    # Add the percentage values on top of the bars
    for i, v in enumerate(side_effect_percentages.values):
        ax.text(i, v + 2, f'{v:.1f}%', ha='center', va='bottom', fontsize=10, color='black')  # Adjust the position and font

    plt.xticks(rotation=90)
    plt.title('Percentage of Patients Experiencing Chemotherapy Side Effects')
    plt.xlabel('Side Effect')
    plt.ylabel('Percentage (%)')
    plt.tight_layout()
    plt.show()

#side effect by stage
def side_effects_by_stage(data):
    side_effect_columns = ['headache', 'dizziness', 'fainting', 'weekness', 'fatigue']
    cancer_stage = data['stage_of_breast_cancer']

    # Plot side effects for each cancer stage
    plt.figure(figsize=(12, 6))
    for effect in side_effect_columns:
        sns.boxplot(x=cancer_stage, y=data[effect], palette='viridis')
        plt.title(f'{effect.capitalize()} Across Cancer Stages')
        plt.xlabel('Cancer Stage')
        plt.ylabel(f'{effect.capitalize()} Occurrence')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()


# Provided treatment data
treatments = [
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Palliative", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)",
    "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Palliative", "Palliative", "Palliative", "Palliative", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)", "Palliative", "Palliative",
    "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)",
    "Palliative", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)", "Palliative",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Palliative",
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Palliative",
    "Adjuvancy (Post-surgery)", "Palliative", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Palliative",
    "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)",
    "Palliative", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Palliative", "Palliative", "Adjuvancy (Post-surgery)", "Adjuvancy (Post-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)", "Palliative",
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)",
    "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)", "Palliative", "Palliative",
    "Adjuvancy (Post-surgery)", "Palliative", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Palliative", "Palliative", "Adjuvancy (Post-surgery)",
    "Palliative", "Palliative", "Adjuvancy (Post-surgery)", "Neo-adjuvancy (Pre-surgery)",
    "Neo-adjuvancy (Pre-surgery)", "Neo-adjuvancy (Pre-surgery)", "Palliative",
    "Neo-adjuvancy (Pre-surgery)", "Adjuvancy (Post-surgery)"
]

# Provided age data
ages = [
    41, 42, 44, 45, 46, 47, 48, 62, 50, 51, 61, 52, 63, 53, 64, 32, 22, 54, 55, 66, 33, 34, 35, 56, 57, 67, 68, 23, 69, 36, 38, 70, 58, 39, 60, 80, 22, 55, 81, 45, 94, 41, 35, 49, 37, 49, 50, 34, 36, 97, 36, 47, 49, 25, 33, 92, 47, 48, 50, 43, 55, 77, 45, 28, 49, 51, 27, 78, 89, 41, 67, 49, 48, 22, 43, 54, 53, 33, 49, 26, 70, 37, 38, 41, 43, 43, 27, 81, 80, 59, 58, 57, 32, 37, 59, 42, 26, 53, 22, 59
]

# Define age groups
age_bins = [0, 20, 30, 40, 50, 60, 70, 80, 90, 100]
age_labels = ['0-20', '21-30', '31-40', '41-50', '51-60', '61-70', '71-80', '81-90', '91-100']

# Create a 2D array to hold counts for each treatment type and age group
treatment_age_counts = {treatment: [0] * (len(age_bins) - 1) for treatment in set(treatments)}

# Count occurrences of each age group for each treatment type
for treatment, age in zip(treatments, ages):
    for i in range(len(age_bins) - 1):
        if age_bins[i] < age <= age_bins[i + 1]:
            treatment_age_counts[treatment][i] += 1
            break

# Prepare data for plotting
x_labels = list(treatment_age_counts.keys())
y_values = np.array([treatment_age_counts[treatment] for treatment in x_labels])

# Create bar graph
plt.figure(figsize=(14, 7)) # Increased figure size for better readability
bar_width = 0.2 # Increased bar width for better spacing
x = np.arange(len(x_labels))

# Create bars for each age group
for i in range(len(age_bins) - 1):
    plt.bar(x + i * bar_width, y_values[:, i], width=bar_width, label=age_labels[i])

plt.xlabel('Type of Treatment')
plt.ylabel('Age of Patients')
plt.title('Recovery of Patients by Treatment Type and Age Group')
plt.xticks(x + bar_width * (len(age_bins) - 2) / 2, x_labels, rotation=30, ha='right') # Adjusted rotation for better visibility
plt.legend(title='Age Groups')
plt.tight_layout()
plt.show()
additional_graphs(data)
side_effect_graph(data)
side_effects_by_stage(data)